config/routes.rb
Rails.application.routes.draw do
  
  root 'home#index'
  resources :users do
    collection do
      get 'sign_up'
      post 'log_in'
    end
  end
  
  # Example of regular route:
  #   get 'products/:id' => 'catalog#view'

  # Example of named route that can be invoked with purchase_url(id: product.id)
  #   get 'products/:id/purchase' => 'catalog#purchase', as: :purchase

  # Example resource route (maps HTTP verbs to controller actions automatically):
  #   resources :products

  # Example resource route with options:
  #   resources :products do
  #     member do
  #       get 'short'
  #       post 'toggle'
  #     end
  #
  #     collection do
  #       get 'sold'
  #     end
  #   end

  # Example resource route with sub-resources:
  #   resources :products do
  #     resources :comments, :sales
  #     resource :seller
  #   end

  # Example resource route with more complex sub-resources:
  #   resources :products do
  #     resources :comments
  #     resources :sales do
  #       get 'recent', on: :collection
  #     end
  #   end

  # Example resource route with concerns:
  #   concern :toggleable do
  #     post 'toggle'
  #   end
  #   resources :posts, concerns: :toggleable
  #   resources :photos, concerns: :toggleable

  # Example resource route within a namespace:
  #   namespace :admin do
  #     # Directs /admin/products/* to Admin::ProductsController
  #     # (app/controllers/admin/products_controller.rb)
  #     resources :products
  #   end
end

app/models/user.rb
class User < ActiveRecord::Base
  # Validations
  validates :username, presence: true, length: { minimum: 5, maximum: 16 }
  validates :password, presence: true, length: { minimum: 5, maximum: 32 }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def show
    @user = User.find(params[:id])
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)

    if @user.save
      render '_sign_up_success'
    else
      render 'new'
    end
  end

  def sign_up
    @user = User.new
    render 'new'
  end

  def log_in
    @user = User.find_by(user_params)

    if @user
      redirect_to @user
    else
      render '_sign_in_error'
    end
  end

  private
    def user_params
      params.require(:user).permit(:username, :password)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/home/index.html.erb
<h1>Checklist App</h1>
<h2>Sign In</h2>

<%= render 'users/sign_in_form' %>

<p>Not a member yet? Sign up <%= link_to 'here', sign_up_users_path %>.</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Checklist</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/users/_form.html.erb
<%= form_for @user, method: 'post', html: { role: 'form' } do |f| %>
  <%= f.label :username %>
  <%= f.text_field :username %>
  <br/>
  <%= f.label :password %>
  <%= f.password_field :password %>
  <br/>
  <%= f.label :confirm %>
  <%= f.password_field :password2 %>
  <br/>
  <%= f.submit 'Create' %>
<% end %>

app/views/users/_sign_in_error.html.erb
<h1>Error!</h1>
<h2>Please check your username and password.</h2>
<h2>Log in <%= link_to 'here', root_path %></h2>

app/views/users/_sign_in_form.html.erb
<%= form_for :user, url: log_in_users_path, method: 'post', html: { role: 'form' } do |f| %>
  <%= f.label :username %>
  <%= f.text_field :username %>
  <br/>
  <%= f.label :password %>
  <%= f.password_field :password %>
  <br/>
  <%= f.submit 'Sign in' %>
<% end %>

app/views/users/_sign_up_success.html.erb
<h1>Your account has been successfully created. </h1>
<h2>Log in <%= link_to 'here', root_path %></h2>

app/views/users/new.html.erb
<h1>Create new account</h1>

<%= render 'form' %>

app/views/users/show.html.erb
<h1>Hello, <%= @user.username %>!</h1>